version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ensure you're using a supported Node.js version
      python: 3.8
    commands:
      - npm install -g aws-cdk
      - npm install
      - pip install -r requirements.txt  # for Python dependencies
  build:
    commands:
      - npm run build  # Build the frontend
      - echo "Environment is ${ENVIRONMENT}"
      - npx cdk synth --output=cdk.out  # Synthesize CloudFormation templates
      - ls cdk.out  # List contents for debugging
      - npm run test  # Run some tests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'cdk.out/ComicCollectionStack*.template.json'
    - '**/*'
  base-directory: 'cdk.out'
  discard-paths: yes
